[32mINFO    [0m BlogPageNew:blog_page_new.py:90 Navigating to blog list: http://localhost:5173/blogs
[32mINFO    [0m BlogPageNew:blog_page_new.py:583 Blog list page loaded successfully
[32mINFO    [0m TestBlogCRUDWorking:test_blog_crud_working.py:170 Guest can see blogs: True
[1m[31mERROR   [0m utils.wait_helpers:wait_helpers.py:80 Element not visible within 3s: ('css selector', "button[data-testid='create-blog'], a[href*='create']")
[1m[31mERROR   [0m BlogPageNew:base_page.py:117 Element not visible: ('css selector', "button[data-testid='create-blog'], a[href*='create']")
[32mINFO    [0m TestBlogCRUDWorking:test_blog_crud_working.py:176 âœ… Guest read access verified
[32mINFO    [0m utils.driver_manager:driver_manager.py:190 WebDriver quit successfully
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF52CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF53170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF53380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF53830>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF53A40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF53C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF537A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF52600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002305BF52AB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13b3375827e6b4829b1ae4267419d346/element
[32mINFO    [0m TestBlogCRUDWorking:test_blog_crud_working.py:127 No logout button found - user not logged in
[32mINFO    [0m TestBlogCRUDWorking:test_blog_crud_working.py:35 âœ… Test completed: test_guest_can_read_blogs